import { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';
import { locales } from '@/i18n';
import { getLocalizedUrl, getAllHreflangUrls, getXDefaultUrl } from '@/utils/locale-utils';
import { SITE_URL } from '@/lib/constants';
import Link from 'next/link';

export function generateStaticParams() {
    return locales.map((locale) => ({ locale }));
}

export async function generateMetadata({ params: { locale } }: { params: { locale: string } }): Promise<Metadata> {
    const t = await getTranslations({ locale, namespace: 'Terms' });
    return {
        title: t('title'),
        description: t('intro'),
        openGraph: { title: t('title'), description: t('intro'), url: getLocalizedUrl(SITE_URL, locale, '/terms'), images: [{ url: `${SITE_URL}/og-image.png`, width: 1200, height: 630 }] },
        twitter: { card: 'summary_large_image', title: t('title'), description: t('intro') },
        alternates: { canonical: getLocalizedUrl(SITE_URL, locale, '/terms'), languages: { 'x-default': getXDefaultUrl(SITE_URL, '/terms'), ...getAllHreflangUrls(SITE_URL, locales, '/terms') } }
    };
}

export default async function TermsPage({ params: { locale } }: { params: { locale: string } }) {
    const t = await getTranslations({ locale, namespace: 'Terms' });

    const sections = [
        { id: 't1', title: t('section1Title'), text: t('section1Text') },
        { id: 't2', title: t('section2Title'), text: t('section2Text') },
        { id: 't3', title: t('section3Title'), text: t('section3Text') },
        {
            id: 't4',
            title: '4. Intellectual Property',
            text: 'All content, tools, and interfaces on Aynzo Tools are the property of the platform. You may not reproduce, distribute, or create derivative works without prior written permission. Tool outputs generated by users belong to the respective users.'
        },
        {
            id: 't5',
            title: '5. Changes to Terms',
            text: 'We reserve the right to update these Terms at any time. Changes will be posted on this page. Your continued use of the service after changes constitutes acceptance of the new terms.'
        },
    ];

    return (
        <div className="min-h-screen bg-background">
            <div className="max-w-6xl mx-auto px-6 py-16 md:py-24">

                {/* Header */}
                <div className="border-b border-border pb-10 mb-10">
                    <p className="text-primary font-bold text-sm uppercase tracking-[0.2em] mb-3">Legal</p>
                    <h1 className="text-4xl md:text-5xl font-black tracking-tight text-foreground mb-4">Terms of Service</h1>
                    <p className="text-muted-foreground text-lg max-w-2xl">{t('intro')}</p>
                    <p className="text-xs text-muted-foreground/60 mt-4 font-medium">Last updated: March 2026</p>
                </div>

                {/* Document layout */}
                <div className="grid lg:grid-cols-4 gap-12">

                    {/* Sticky TOC */}
                    <div className="hidden lg:block">
                        <div className="sticky top-24">
                            <p className="text-xs font-black uppercase tracking-widest text-muted-foreground mb-4">On this page</p>
                            <nav className="space-y-2">
                                {sections.map((s) => (
                                    <a key={s.id} href={`#${s.id}`} className="block text-sm text-muted-foreground hover:text-primary transition-colors py-1 border-l-2 border-border hover:border-primary pl-3">
                                        {s.title}
                                    </a>
                                ))}
                            </nav>
                            <div className="mt-8 pt-6 border-t border-border">
                                <p className="text-xs text-muted-foreground mb-3">Also read</p>
                                <Link href="/privacy" className="block text-sm text-primary hover:underline font-medium">Privacy Policy →</Link>
                            </div>
                        </div>
                    </div>

                    {/* Content */}
                    <div className="lg:col-span-3 space-y-12">
                        {sections.map((section) => (
                            <div key={section.id} id={section.id} className="scroll-mt-24">
                                <h2 className="text-xl font-black text-foreground mb-4 pb-3 border-b border-border">
                                    {section.title}
                                </h2>
                                <p className="text-muted-foreground leading-relaxed">{section.text}</p>
                            </div>
                        ))}

                        <div className="mt-12 p-6 bg-secondary/40 rounded-2xl border border-border">
                            <p className="text-sm font-bold text-foreground mb-1">Questions?</p>
                            <p className="text-sm text-muted-foreground">
                                Email us at <a href="mailto:support@aynzo.com" className="text-primary font-semibold hover:underline">support@aynzo.com</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
